### ISSUE TITLE
"The bot is not verified"

### ISSUE THREAD

**Issue by DanteDeRuwe** [vexuas/nessie#44]
![image](https://user-images.githubusercontent.com/23363437/153240609-8c9be7b7-8abd-4fc0-8335-7455eb9fabc1.png)

Hoping you could fix this. Seems like a great bot, but I cannot invite it. Thanks in advance

**Comment by vexuas** [comment]
Hi there! Thanks for opening an issue :D Currently nessie is in 100 servers and that's the limit a bot can be in until it gets officially verified by Discord. I have started the verification process and Discord has reached out with requests before it can be finalized

These requests are addressed with the release of #46. I'll get back to you once that's out and I hear from Discord!

**Comment by DanteDeRuwe** [comment]
Great! I should've looked a bit closer at the work you are doing here first. I just saw your explanation on the releases page. Good luck!

**Comment by vexuas** [comment]
Hey @DanteDeRuwe! I finally got a response from Discord and Nessie is now verified! 🎉  You can invite her through this [link](https://discord.com/oauth2/authorize?client_id=889135055430111252&permissions=2064&scope=applications.commands%20bot)

**Comment by DanteDeRuwe** [comment]
Great! 🎉
